app: apaas-token
stage: prod # The debugger only for test env.

component: http
name: application

inputs:
  src:
    src: ./
    exclude:
      - .env
      - .env.local
  region: ap-guangzhou
  faas:
    runtime: Nodejs12.16
    framework: koa
    name: ${name}-${stage}-${app}
    timeout: 10
    environments:
      - key: REGION
        value: ap-guangzhou
      - key: STAGE
        value: ${stage}
      - key: APAAS_APPID
        value: ${env:APAAS_APPID}
      - key: APAAS_SECRET
        value: ${env:APAAS_SECRET}
  apigw:
    isDisabled: false
    environment: release
    id: ${output:${stage}:${app}:apaas_token_apigw.serviceId}
    name: apaas_token_apigw
    api:
      path: /
      cors: true
      timeout: 30
      qualifier: $DEFAULT
    protocols:
      - http
      - https

# https://github.com/serverless-components/tencent-http/blob/master/docs/configure.md